config/routes.rb
Rails.application.routes.draw do
  post "order/create"
  resources :addresses
  get "shipping_info/show"
  get "about_page/index"
  get "products/cart", to: "products#cart"
  get "cart", to: "cart#show"

  post "cart/add"
  post "cart/remove"

  post "address/tax"

  resources :shipping_info
  resources :products
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :customers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"

  # resources :cart, only: %i[create destroy]
end

app/models/about_page.rb
class AboutPage < ApplicationRecord
  validates :Title, :Content, presence: true
end

app/models/address.rb
class Address < ApplicationRecord
  validates :name, :address, :city, :province, :email, presence: true

  has_many :orders
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :orderables
  has_many :products, through: :orderables

  def total
    orderables.to_a.sum { |orderable| orderable.total }
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, presence: true, uniqueness: true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :full_name, :phone_number, :email, presence: true, uniqueness: true

  has_one_attached :image
  has_many :orders

  def self.search(search)
    if search
      keyword = "%" + search + "%"
      @customers = Customer.where("full_name LIKE ? OR phone_number LIKE ?", keyword, keyword)
    else
      Customer.all
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :address
  belongs_to :customer
  belongs_to :cart
end

app/models/orderable.rb
class Orderable < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total
    product.price * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :manufacture, :style, :cost, presence: true

  belongs_to :category
  has_one_attached :image
  has_many :orderables
  has_many :carts, through: :orderables

  def self.search(search)
    categoryArray = []
    @categories = Category.all

    @categories.each do |c|
      categoryArray.push(c.id)
    end

    if search
      if categoryArray.include? search.to_i
        @products = Product.where("category_id = ?", search)
      else
        keyword = "%" + search + "%"
        @products = Product.where("name LIKE ? OR manufacture LIKE ? OR comment LIKE ?", keyword,
                                  keyword, keyword)
      end
    else
      Product.all
    end
  end

  paginates_per 24
end

app/models/tax.rb
class Tax < ApplicationRecord
  validates :name, :gst, :pst, presence: true, uniqueness: true
end

app/controllers/addresses_controller.rb
class AddressesController < InheritedResources::Base
  # GET /addresses or /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1 or /addresses/1.json
  def show
    @address = Address.find(params[:id])
    @tax = Tax.find_by(name: @address.province)
  end

  # GET /addresses/new
  def new
    @taxes = Tax.all
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
    @taxes = Tax.all
    @address = Address.find(params[:id])
  end

  # POST /addresses or /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html do
          redirect_to address_url(@address), notice: "Address was successfully created."
        end
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1 or /addresses/1.json
  def update
    @address = Address.find(params[:id])
    respond_to do |format|
      if @address.update(address_params)
        format.html do
          redirect_to address_url(@address), notice: "Address was successfully updated."
        end
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1 or /addresses/1.json
  def destroy
    @address = Address.find(params[:id])
    redirect_to cart_path if @address.destroy
  end

  private

  def address_params
    params.require(:address).permit(:name, :address, :city, :province, :email)
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @render_cart = false
  end

  def add
    @product = Product.find_by(id: params[:id])
    quantity = params[:quantity].to_i
    current_orderable = @cart.orderables.find_by(product_id: @product.id)
    if current_orderable && quantity > 0
      current_orderable.update(quantity: quantity)
    elsif quantity <= 0
      current_orderable.destroy
    else
      @cart.orderables.create(product: @product, quantity: quantity)
    end

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [turbo_stream.replace("cart",
                                                   partial: "cart/cart",
                                                   locals:  { cart: @cart }),
                              turbo_stream.replace(@orderable)]
      end
    end
  end

  def remove
    Orderable.find_by(id: params[:id]).destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace("cart",
                                                  partial: "cart/cart",
                                                  locals:  { cart: @cart })
      end
    end
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def create
    address_id = params[:address_id].to_i
    cart_id = params[:cart_id].to_i
    subtotal = params[:subtotal].to_i
    pst = params[:pst].to_i
    gst = params[:gst].to_i

    @order = Order.new(address_id: address_id, customer_id: 1, cart_id: cart_id, subtotal: subtotal, pst: pst,
                       gst: gst)

    redirect_to root_path, notice: "Order was successfully created." if @order.save
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.search(params[:search]).page(params[:page])
    @categories = Category.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def cart
    @products = Product.where(id: session[:shopping_cart])
  end

  private

  def product_params
    params.require(:product).permit(:name, :manufacture, :style, :cost, :price, :comment)
  end
end

app/helpers/about_page_helper.rb
module AboutPageHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/_cart.html.erb
<%= turbo_frame_tag "cart" do %>
<% if @cart.orderables.count > 0 %>
  <%= render "cart/orderables" %>
  <% else %>
  <h1>🛒 is empty</h1>
  <% end %>
<% end %>

app/views/cart/_orderables.html.erb
<section class="section">
  <div class="container">
    <section class="section products-table">
      <div class="columns table-header">
        <div class="column">Image</div>
        <div class="column">Product Description</div>
        <div class="column">Price</div>
        <div class="column">Quantity</div>
        <div class="column"></div>
      </div>
      <div id="shopping_cart">
        <div>
            <% @cart.orderables.each do |orderable| %>
              <% product = orderable.product %>
              <div class="columns product-row" id="<%= dom_id orderable %>">
                <div class="column product-image">
                  <%= image_tag(product.image, alt:"product_img") %>
                </div>
                <div class="column center-container">
                  <%= product.manufacture + ' ' + product.name %>
                </div>
                <div class="column center-container">
                  <%= number_to_currency product.price %>
                </div>
                <div class="column center-container">
                    <%= form_with(url: cart_add_path) do |f| %>
                        <%= f.hidden_field :id, value: product.id %>
                        <%= f.number_field :quantity, value: orderable.quantity, min: 0 %>
                        <%= f.submit "Update" %>
                    <% end %>
                    <%= form_with(url: cart_remove_path) do |f| %>
                        <%= f.hidden_field :id, value: orderable.id %>
                        <%= f.submit "Remove" %>
                    <% end %>
                </div>
              </div>
            <% end %>
        </div>
      </div>
    </section>
    <section class="columns checkout">
        <div class="column submit-form">
            <div id="total">
            <span class="total">Subtotal: <%= number_to_currency @cart.total %> </span>
            </div>
            <div class="field is-grouped">
            <div class="column center-container">
                <%= button_to "Continue to Checkout", new_address_path, :method => :get %>
            </div>
            </div>
        </div>
    </section>
  </div>
</section>

app/views/cart/show.html.erb
<%= render partial: "cart/cart" %>

app/views/order/create.html.erb
<h1>Order#create</h1>
<p>Find me in app/views/order/create.html.erb</p>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :manufacture, style: "display: block" %>
    <%= form.text_field :manufacture %>
  </div>

  <div>
    <%= form.label :style, style: "display: block" %>
    <%= form.text_field :style %>
  </div>

  <div>
    <%= form.label :cost, style: "display: block" %>
    <%= form.text_field :cost %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :comment, style: "display: block" %>
    <%= form.text_area :comment %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="column is-one-quarter-table is-one-third-desktop" id="<%= dom_id product %>">
  <div class="card">
    <div class="card-image hast-text-centered px-6">
      <% if product.image.present? %>
        <figure class="image">
          <%= image_tag(product.image, alt: "product_img") %>
        </figure>
      <%end%>
    </div>
    <div class="card-content">
      <p class="subtitle is-6"><%= product.manufacture %></p>
      <p class="title is-4"><%= product.name %></p>
      <p class="subtitle is-8"><%= number_to_currency product.price %></p>
    </div>
    <footer class="card-footer">
      <p>
        <%= link_to "View", product %>
      </p>
    </footer>
  </div>
</div>

app/views/products/cart.html.erb
<section class="section">
  <div class="container">
    <section class="section products-table">
      <div class="columns table-header">
        <div class="column">Image</div>
        <div class="column">Product Description</div>
        <div class="column">Price</div>
        <div class="column">Quantity</div>
      </div>
      <div id="shopping_cart">
        <div>
            <% @products.each do |product| %>
              <div class="columns product-row">
                <div class="column product-image">
                  <%= image_tag(product.image, alt:"product_img") %>
                </div>
                <div class="column center-container">
                  <%= product.manufacture + ' ' + product.name %>
                </div>
                <div class="column center-container">
                  $<%= number_to_currency product.price %>
                </div>
                <div class="column center-container">
                  <label for=<%= product.id %> class="mobile-table-heading"> Quantity</label >
                  <input id=<%= product.id %> class="quantity" type="number" name="quantity" min="1" max="10" value="1">
                </div>
              </div>
            <% end %>
        </div>
      </div>
    </section>

    <section class="columns checkout">
      <div class="column submit-form">
        <div id="total">
          <span class="total">Total $34.97 </span>
        </div>
        <div class="field is-grouped">
          <p class="control">
            <button class="button is-link" href="#">Continue to checkout</button>
          </p>
        </div>
      </div>
    </section>
  </div>
</section>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<% if flash[:notice] %>
  <p style="color: green"><%= notice %></p>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-multiline mt-5 is-8 is-variable" id="products">
      <% @products.each do |product| %>
        <%= render product %>
      <% end %>
    </div>
  </div>
</section>

<section class="page_section">
  <div class="container">
    <div class="columns is-centered">
      <%= paginate @products %>
    </div>
  </div>
</section>
 <!--
<%= form_with(scope: "category") do |f| %>
  <%= f.select :id, @categories.map { |c| [c.name, c.id] } %>
<% end %>
 -->

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

  <section class="section">
    <div class="container">
      <div class="tile is-ancestor">
        <div class="tile is-vertical is-8">
          <div class="tile">
            <div class="tile is-parent is-vertical">
              <article class="tile is-child notification is-primary">
                <p class="title"><%= @product.name %></p>
                <p class="subtitle"><%= @product.manufacture %></p>
                <p class="subtitle"><%= number_to_currency @product.price %></p>
                <div class="has-text-right">

                  <%= form_with(url: cart_add_path) do |f| %>
                    <%= f.hidden_field :id, value: @product.id %>
                    <%= f.hidden_field :quantity, value: 1 %>
                    <%= f.submit "Add to Cart" %>
                  <% end %>

                </div>
              </article>
              <article class="tile is-child notification is-warning">
                <p class="title">Description</p>
                <p class="subtitle"><%= @product.comment %></p>
              </article>
            </div>
            <div class="tile is-parent">
              <article class="tile is-child notification is-info">
                <% if @product.image.present? %>
                  <figure class="image">
                    <%= image_tag(@product.image, alt:"product_img") %>
                  </figure>
                <%end%>
              </article>
            </div>
          </div>
        </div>
      </div>
      <div>
        <%= link_to "Back to product list", products_path %>
      </div>
    </div>
  </section>