config/routes.rb
Rails.application.routes.draw do
  post "order/create"
  resources :addresses
  get "shipping_info/show"
  get "about_page/index"
  get "products/cart", to: "products#cart"
  get "cart", to: "cart#show"

  post "cart/add"
  post "cart/remove"

  post "address/tax"

  resources :shipping_info
  resources :products
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :customers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"

  # resources :cart, only: %i[create destroy]
end

app/models/about_page.rb
class AboutPage < ApplicationRecord
  validates :Title, :Content, presence: true
end

app/models/address.rb
class Address < ApplicationRecord
  validates :name, :address, :city, :province, :email, presence: true

  has_many :orders
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :orderables
  has_many :products, through: :orderables

  def total
    orderables.to_a.sum { |orderable| orderable.total }
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, presence: true, uniqueness: true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :full_name, :phone_number, :email, presence: true, uniqueness: true

  has_one_attached :image
  has_many :orders

  def self.search(search)
    if search
      keyword = "%" + search + "%"
      @customers = Customer.where("full_name LIKE ? OR phone_number LIKE ?", keyword, keyword)
    else
      Customer.all
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :address
  belongs_to :customer
  belongs_to :cart
end

app/models/orderable.rb
class Orderable < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total
    product.price * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :manufacture, :style, :cost, presence: true

  belongs_to :category
  has_one_attached :image
  has_many :orderables
  has_many :carts, through: :orderables

  def self.search(search)
    categoryArray = []
    @categories = Category.all

    @categories.each do |c|
      categoryArray.push(c.id)
    end

    if search
      if categoryArray.include? search.to_i
        @products = Product.where("category_id = ?", search)
      else
        keyword = "%" + search + "%"
        @products = Product.where("name LIKE ? OR manufacture LIKE ? OR comment LIKE ?", keyword,
                                  keyword, keyword)
      end
    else
      Product.all
    end
  end

  paginates_per 24
end

app/models/tax.rb
class Tax < ApplicationRecord
  validates :name, :gst, :pst, presence: true, uniqueness: true
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @render_cart = false
  end

  def add
    @product = Product.find_by(id: params[:id])
    quantity = params[:quantity].to_i
    current_orderable = @cart.orderables.find_by(product_id: @product.id)
    if current_orderable && quantity > 0
      current_orderable.update(quantity: quantity)
    elsif quantity <= 0
      current_orderable.destroy
    else
      @cart.orderables.create(product: @product, quantity: quantity)
    end

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [turbo_stream.replace("cart",
                                                   partial: "cart/cart",
                                                   locals:  { cart: @cart }),
                              turbo_stream.replace(@orderable)]
      end
    end
  end

  def remove
    Orderable.find_by(id: params[:id]).destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace("cart",
                                                  partial: "cart/cart",
                                                  locals:  { cart: @cart })
      end
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[show edit update destroy]

  # GET /customers or /customers.json
  def index
    @customers = Customer.search(params[:search])
  end

  # GET /customers/1 or /customers/1.json
  def show; end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit; end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html do
          redirect_to customer_url(@customer), notice: "Customer was successfully created."
        end
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html do
          redirect_to customer_url(@customer), notice: "Customer was successfully updated."
        end
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_customer
    @customer = Customer.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def customer_params
    params.require(:customer).permit(:full_name, :phone_number, :email, :notes, :search)
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def create
    address_id = params[:address_id].to_i
    cart_id = params[:cart_id].to_i
    subtotal = params[:subtotal].to_i
    pst = params[:pst].to_i
    gst = params[:gst].to_i

    @order = Order.new(address_id: address_id, customer_id: 1, cart_id: cart_id, subtotal: subtotal, pst: pst,
                       gst: gst)

    redirect_to root_path, notice: "Order was successfully created." if @order.save
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.search(params[:search]).page(params[:page])
    @categories = Category.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def cart
    @products = Product.where(id: session[:shopping_cart])
  end

  private

  def product_params
    params.require(:product).permit(:name, :manufacture, :style, :cost, :price, :comment)
  end
end

app/helpers/about_page_helper.rb
module AboutPageHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/customers/_customer.html.erb
<div id="<%= dom_id customer %>">
  <p>
    <strong>Full name:</strong>
    <%= customer.full_name %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= customer.phone_number %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= customer.email %>
  </p>

  <p>
    <strong>Notes:</strong>
    <%= customer.notes %>
  </p>

  <p>
    <div class="card-image">
      <% if customer.image.present? %>
        <figure class="image">
          <%= image_tag customer.image %>
        </figure>
      <%end%>
    </div>
  </p>

</div>

app/views/customers/_form.html.erb
<%= form_with(model: customer) do |form| %>
  <% if customer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :full_name, style: "display: block" %>
    <%= form.text_field :full_name %>
  </div>

  <div>
    <%= form.label :phone_number, style: "display: block" %>
    <%= form.text_field :phone_number %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :notes, style: "display: block" %>
    <%= form.text_area :notes %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render "form", customer: @customer %>

<br>

<div>
  <%= link_to "Show this customer", @customer %> |
  <%= link_to "Back to customers", customers_path %>
</div>

app/views/customers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Customers</h1>

<%= form_tag(customers_path, method: :get) do %>
  <%= text_field_tag(:search, params[:search]) %>
  <%= submit_tag ("Search") %>
<% end %>

<section id="customers">
  <% @customers.each do |customer| %>
    <aside>
      <%= render customer %>
      <p>
        <%= link_to "Show this customer", customer %>
      </p>
    </aside>
  <% end %>
</section>

<%= link_to "New customer", new_customer_path %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render "form", customer: @customer %>

<br>

<div>
  <%= link_to "Back to customers", customers_path %>
</div>

app/views/customers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @customer %>

<div>
  <%= link_to "Edit this customer", edit_customer_path(@customer) %> |
  <%= link_to "Back to customers", customers_path %>
  <%= button_to "Destroy this customer", @customer, method: :delete %>
</div>