config/routes.rb
Rails.application.routes.draw do
  post "order/create"
  resources :addresses
  get "shipping_info/show"
  get "about_page/index"
  get "products/cart", to: "products#cart"
  get "cart", to: "cart#show"

  post "cart/add"
  post "cart/remove"

  post "address/tax"

  resources :shipping_info
  resources :products
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :customers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"

  # resources :cart, only: %i[create destroy]
end

app/models/about_page.rb
class AboutPage < ApplicationRecord
  validates :Title, :Content, presence: true
end

app/models/address.rb
class Address < ApplicationRecord
  validates :name, :address, :city, :province, :email, presence: true

  has_many :orders
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :orderables
  has_many :products, through: :orderables

  def total
    orderables.to_a.sum { |orderable| orderable.total }
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, presence: true, uniqueness: true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :full_name, :phone_number, :email, presence: true, uniqueness: true

  has_one_attached :image
  has_many :orders

  def self.search(search)
    if search
      keyword = "%" + search + "%"
      @customers = Customer.where("full_name LIKE ? OR phone_number LIKE ?", keyword, keyword)
    else
      Customer.all
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :address
  belongs_to :customer
  belongs_to :cart
end

app/models/orderable.rb
class Orderable < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total
    product.price * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :manufacture, :style, :cost, presence: true

  belongs_to :category
  has_one_attached :image
  has_many :orderables
  has_many :carts, through: :orderables

  def self.search(search)
    categoryArray = []
    @categories = Category.all

    @categories.each do |c|
      categoryArray.push(c.id)
    end

    if search
      if categoryArray.include? search.to_i
        @products = Product.where("category_id = ?", search)
      else
        keyword = "%" + search + "%"
        @products = Product.where("name LIKE ? OR manufacture LIKE ? OR comment LIKE ?", keyword,
                                  keyword, keyword)
      end
    else
      Product.all
    end
  end

  paginates_per 24
end

app/models/tax.rb
class Tax < ApplicationRecord
  validates :name, :gst, :pst, presence: true, uniqueness: true
end

app/controllers/addresses_controller.rb
class AddressesController < InheritedResources::Base
  # GET /addresses or /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1 or /addresses/1.json
  def show
    @address = Address.find(params[:id])
    @tax = Tax.find_by(name: @address.province)
  end

  # GET /addresses/new
  def new
    @taxes = Tax.all
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
    @taxes = Tax.all
    @address = Address.find(params[:id])
  end

  # POST /addresses or /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html do
          redirect_to address_url(@address), notice: "Address was successfully created."
        end
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1 or /addresses/1.json
  def update
    @address = Address.find(params[:id])
    respond_to do |format|
      if @address.update(address_params)
        format.html do
          redirect_to address_url(@address), notice: "Address was successfully updated."
        end
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1 or /addresses/1.json
  def destroy
    @address = Address.find(params[:id])
    redirect_to cart_path if @address.destroy
  end

  private

  def address_params
    params.require(:address).permit(:name, :address, :city, :province, :email)
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @render_cart = false
  end

  def add
    @product = Product.find_by(id: params[:id])
    quantity = params[:quantity].to_i
    current_orderable = @cart.orderables.find_by(product_id: @product.id)
    if current_orderable && quantity > 0
      current_orderable.update(quantity: quantity)
    elsif quantity <= 0
      current_orderable.destroy
    else
      @cart.orderables.create(product: @product, quantity: quantity)
    end

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [turbo_stream.replace("cart",
                                                   partial: "cart/cart",
                                                   locals:  { cart: @cart }),
                              turbo_stream.replace(@orderable)]
      end
    end
  end

  def remove
    Orderable.find_by(id: params[:id]).destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace("cart",
                                                  partial: "cart/cart",
                                                  locals:  { cart: @cart })
      end
    end
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def create
    address_id = params[:address_id].to_i
    cart_id = params[:cart_id].to_i
    subtotal = params[:subtotal].to_i
    pst = params[:pst].to_i
    gst = params[:gst].to_i

    @order = Order.new(address_id: address_id, customer_id: 1, cart_id: cart_id, subtotal: subtotal, pst: pst,
                       gst: gst)

    redirect_to root_path, notice: "Order was successfully created." if @order.save
  end
end

app/helpers/about_page_helper.rb
module AboutPageHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/addresses/_address.html.erb
<div id="<%= dom_id address %>">
  <p>
    <strong>Name:</strong>
    <%= address.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= address.address %>
  </p>

  <p>
    <strong>City:</strong>
    <%= address.city %>
  </p>

  <p>
    <strong>Province:</strong>
    <%= address.province %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= address.email %>
  </p>

</div>

app/views/addresses/_form.html.erb
<%= form_with(model: address) do |form| %>
  <% if address.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
        <% address.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :email, style: "display: block" %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :province, style: "display: block" %>
    <div class="select">
        <%= form.select :province, @taxes.map { |c| [c.name, c.name] }, {:include_blank => true}  %>
    </div>
  </div>

    <section class="columns checkout">

        <div class="column submit-form" id="<%= dom_id @cart %>">
            <div id="subtotal">
            <span class="subtotal">Subtotal: <%= number_to_currency @cart.total %> </span>
            </div>
            <% if @tax %>
                <div id="pst">
                <span class="subtotal">Tax: <%= number_to_currency @tax.pst * @cart.total %> </span>
                </div>

                <div id="gst">
                <span class="subtotal">Tax: <%= number_to_currency @tax.gst * @cart.total %> </span>
                </div>

                <div id="total">
                <span class="subtotal">Total: <%= number_to_currency @cart.total * (1 + @tax.pst + @tax.gst) %> </span>
                </div>
            <% end %>

            <div class="field is-grouped">
                <div class="field is-grouped">
                <div class="control">
                    <%= form.submit "Continue to payment", style: "display: block" %>
                </div>
                <div class="control">
                    <%= link_to "Back to Shopping Cart", address, method: :delete %>
                </div>
                </div>
            </div>
        </div>
    </section>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing address</h1>

<%= render "form", address: @address %>

app/views/addresses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Addresses</h1>

<div id="addresses">
  <% @addresses.each do |address| %>
    <%= render address %>
    <p>
      <%= link_to "Show this address", address %>
    </p>
  <% end %>
</div>

<%= link_to "New address", new_address_path %>

app/views/addresses/new.html.erb
<h1>Shipping address</h1>
<section class="section">
  <div class="container">

<%= turbo_frame_tag "tax" do %>

    <%= render "form", address: @address %>

<% end %>

  </div>
</section>

app/views/addresses/show.html.erb
<p style="color: green"><%= notice %></p>

<section class="section address-table">
  <div id="<%= dom_id @address %>">
    <p><strong>Shipping Address:</strong></p>
    <p>
      Name:
      <%= @address.name %>
    </p>

    <p>
      Address:
      <%= @address.address %>
    </p>

    <p>
      City:
      <%= @address.city %>
    </p>

    <p>
      Province:
      <%= @address.province %>
    </p>

    <p>
      Email:
      <%= @address.email %>
    </p>

  </div>
</section>

<section class="section">
  <div class="container">
    <section class="section products-table">
      <div class="columns table-header">
        <div class="column">Product Description</div>
        <div class="column">Price</div>
        <div class="column">Quantity</div>
      </div>
      <div id="shopping_cart">
        <div>
            <% @cart.orderables.each do |orderable| %>
              <% product = orderable.product %>
              <div class="columns product-row" id="<%= dom_id orderable %>">
                <div class="column center-container">
                  <%= product.manufacture + ' ' + product.name %>
                </div>
                <div class="column center-container">
                  <%= number_to_currency product.price %>
                </div>
                <div class="column center-container">
                    <%= form_with(url: cart_add_path) do |f| %>
                      <%= orderable.quantity %>
                    <% end %>
                </div>
              </div>
            <% end %>
        </div>
      </div>
    </section>

    <section class="columns checkout">
        <div class="column submit-form">
            <div id="total">
            <span class="total">Subtotal: <%= number_to_currency @cart.total %> </span>
            </div>

            <% if @tax %>
                <div id="pst_amount">
                <span class="subtotal">PST: <%= number_to_currency @tax.pst * @cart.total %> </span>
                </div>

                <div id="gst_amount">
                <span class="subtotal">GST: <%= number_to_currency @tax.gst * @cart.total %> </span>
                </div>

                <div id="total_amount">
                <span class="subtotal"> <strong>Total:</strong>  <%= number_to_currency @cart.total * (1 + @tax.pst + @tax.gst) %> </span>
                </div>
            <% end %>

            <div class="field is-grouped">
                <div class="field is-grouped">
                <div class="control">

                  <%= form_with(url: order_create_path) do |f| %>
                      <%= f.hidden_field :address_id, value: @address.id %>
                      <%= f.hidden_field :cart_id, value: @cart.id %>
                      <%= f.hidden_field :subtotal, value: (@cart.total * 100).to_i %>
                      <%= f.hidden_field :pst, value: (@tax.pst * @cart.total * 100).to_i %>
                      <%= f.hidden_field :gst, value: (@tax.gst * @cart.total * 100).to_i %>
                      <%= f.submit "Checkout" %>
                  <% end %>

                </div>
                <div class="control">
                    <%= link_to "Edit this address", edit_address_path(@address) %>
                </div>
                </div>
            </div>

        </div>
    </section>
  </div>
</section>