config/routes.rb
Rails.application.routes.draw do
  post "order/create"
  resources :addresses
  get "shipping_info/show"
  get "about_page/index"
  get "products/cart", to: "products#cart"
  get "cart", to: "cart#show"

  post "cart/add"
  post "cart/remove"

  post "address/tax"

  resources :shipping_info
  resources :products
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :customers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"

  # resources :cart, only: %i[create destroy]
end

app/models/about_page.rb
class AboutPage < ApplicationRecord
  validates :Title, :Content, presence: true
end

app/models/address.rb
class Address < ApplicationRecord
  validates :name, :address, :city, :province, :email, presence: true

  has_many :orders
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :orderables
  has_many :products, through: :orderables

  def total
    orderables.to_a.sum { |orderable| orderable.total }
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, presence: true, uniqueness: true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :full_name, :phone_number, :email, presence: true, uniqueness: true

  has_one_attached :image
  has_many :orders

  def self.search(search)
    if search
      keyword = "%" + search + "%"
      @customers = Customer.where("full_name LIKE ? OR phone_number LIKE ?", keyword, keyword)
    else
      Customer.all
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :address
  belongs_to :customer
  belongs_to :cart
end

app/models/orderable.rb
class Orderable < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total
    product.price * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :manufacture, :style, :cost, presence: true

  belongs_to :category
  has_one_attached :image
  has_many :orderables
  has_many :carts, through: :orderables

  def self.search(search)
    categoryArray = []
    @categories = Category.all

    @categories.each do |c|
      categoryArray.push(c.id)
    end

    if search
      if categoryArray.include? search.to_i
        @products = Product.where("category_id = ?", search)
      else
        keyword = "%" + search + "%"
        @products = Product.where("name LIKE ? OR manufacture LIKE ? OR comment LIKE ?", keyword,
                                  keyword, keyword)
      end
    else
      Product.all
    end
  end

  paginates_per 24
end

app/models/tax.rb
class Tax < ApplicationRecord
  validates :name, :gst, :pst, presence: true, uniqueness: true
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @render_cart = false
  end

  def add
    @product = Product.find_by(id: params[:id])
    quantity = params[:quantity].to_i
    current_orderable = @cart.orderables.find_by(product_id: @product.id)
    if current_orderable && quantity > 0
      current_orderable.update(quantity: quantity)
    elsif quantity <= 0
      current_orderable.destroy
    else
      @cart.orderables.create(product: @product, quantity: quantity)
    end

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [turbo_stream.replace("cart",
                                                   partial: "cart/cart",
                                                   locals:  { cart: @cart }),
                              turbo_stream.replace(@orderable)]
      end
    end
  end

  def remove
    Orderable.find_by(id: params[:id]).destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace("cart",
                                                  partial: "cart/cart",
                                                  locals:  { cart: @cart })
      end
    end
  end
end

app/helpers/about_page_helper.rb
module AboutPageHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simplitcity Bike store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
  </head>

  <body>
    <header>
      <nav class="navbar has-shadow is-white">
        <div class="navbar-brand">
          <a class="navbar-item">
            <%= image_tag("logos/logo.png", style: 'max-height: 180px', alt: 'logo')%>
          </a>
          <a class="navbar-burger" id="burger">
            <span></span>
            <span></span>
            <span></span>
          </a>
        </div>
        <div class="navbar-menu is-size-5 is-align-items-self-end" id="nav-links">
          <div class="navbar-end">

            <%= form_tag(products_path, method: :get, class: "navbar-item") do %>
              <%= text_field_tag(:search, params[:search]) %>
              <%= submit_tag ("Search") %>
            <% end %>

            <%= link_to "Home", products_path, class: "navbar-item" %>

            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">
                Categories
              </a>

              <div class="navbar-dropdown">

                <%= link_to "Hard Tail", "http://localhost:3000/products?search=23&commit=Search", class: "navbar-item" %>
                <%= link_to "Full Suspension", "http://localhost:3000/products?search=24&commit=Search", class: "navbar-item" %>
                <%= link_to "Gravel", "http://localhost:3000/products?search=26&commit=Search", class: "navbar-item" %>
                <%= link_to "Performance", "http://localhost:3000/products?search=25&commit=Search", class: "navbar-item" %>
              </div>
            </div>
            <%= link_to "🛒", cart_path, class: "navbar-item" %>
            <%= link_to "About", about_page_index_path, class: "navbar-item" %>
          </div>
        </div>
      </nav>

      <!-- breadcrumbs
      <div class="section pt-4 pb-0">
        <nav class="breadcrumb has-arrow-separator">
          <ul class="container is-size-6">
            <li><a class="has-text-grey">Home</a></li>
            <li><a class="has-text-grey">Categories</a></li>
            <li class="is-active"><a>Bikes</a></li>
          </ul>
        </nav>
      </div> -->

    </header>

    <%= yield %>

    <footer class="footer">
      <div class="content has-text-centered">
        <p>Copy Cat <%= Time.current.year %></p>
      </div>
    </footer>

  </body>

</html>